import fs from "fs";
import path from "path";
import type { LoadOptions } from "../types.js";
import { isClientFramework, isPublicKey, normalize } from "../lib/utils.js";

/**
 * Generate a centralized `env.ts` file with all loaded environment variables.
 * Respects user-defined files.
 * @param keys Set of environment variable names to export
 */
export function generateEnvFileImpl(
  keys: string[],
  generateEnvFile: LoadOptions["generateEnvFile"],
) {
  const isClient = isClientFramework();
  const shouldSkip =
    isClient ||
    !generateEnvFile ||
    keys.length === 0 ||
    process.env.NODE_ENV === "production";

  if (shouldSkip) return;

  const cwd = process.cwd();

  const outputPath =
    typeof generateEnvFile === "string"
      ? generateEnvFile
      : path.resolve(cwd, "env.ts");

  // Determine target directory: src/lib if src exists, else lib
  const srcDir = path.join(cwd, "src");
  let targetDir: string;

  if (typeof generateEnvFile === "string") {
    targetDir = path.dirname(generateEnvFile);
  } else {
    if (fs.existsSync(srcDir)) {
      targetDir = path.join(srcDir, "lib");
    } else {
      targetDir = path.join(cwd, "lib");
    }
  }

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const filename = path.basename(outputPath);
  const filePath = path.join(targetDir, filename);

  // prepend NODE_ENV to keys
  const keysArray = Array.from(new Set(["NODE_ENV", ...keys]));

  const nonPublicKeys = keysArray.filter((key) => !isPublicKey(key));

  if (nonPublicKeys.length === 0) return;

  const exportBlock = `export const {
${nonPublicKeys.map((key) => `  ${key},`).join("\n")}
} = process.env;`;

  const fileContent = `// Auto-generated by @explita/env-loader
// Do not edit manually
// import "@explita/env-loader/auto";

${exportBlock}
`;

  let existingContent = "";
  try {
    existingContent = fs.readFileSync(filePath, "utf8");
  } catch {
    // file doesn't exist yet
  }

  // Respect user-defined files
  if (
    existingContent &&
    !existingContent.includes("Auto-generated by @explita/env-loader")
  ) {
    console.log(
      `[env-loader]: ⚠️ ${filePath} exists and appears to be user-defined. Skipping update.`,
    );
    return;
  }

  // Only write/update if our content changed or file is empty
  if (normalize(existingContent) !== normalize(fileContent)) {
    fs.writeFileSync(filePath, fileContent, "utf8");
    console.log(
      `[env-loader]: ✨ Generated ${filename}: ${filePath} (${nonPublicKeys.length} keys)`,
    );
  }
}
