import fs from "fs";
import path from "path";
import { LoadOptions } from "../types";
import { updateFiles } from "./update-files";

/**
 * Generate TypeScript declaration file
 */
export function generateEnvTypes(
  keys: Set<string>,
  generateTypes: LoadOptions["generateTypes"]
): void {
  if (!generateTypes || keys.size === 0) return;

  const outputPath =
    typeof generateTypes === "string"
      ? generateTypes
      : path.resolve(process.cwd(), "env.d.ts");

  const keysArray = Array.from(keys)
    .sort()
    .filter((k) => k !== "NODE_ENV");

  // Filter out Next.js/Vite public variables (they have special handling)
  const isPublicKey = (key: string) =>
    key.startsWith("NEXT_PUBLIC_") || key.startsWith("VITE_");

  const nonPublicKeys = keysArray.filter((key) => !isPublicKey(key));
  const publicKeys = keysArray.filter(isPublicKey);

  const declarationContent = `// Auto-generated by @explita/env-loader
// Total variables: ${keysArray.length}

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      // Node.js built-in
      NODE_ENV: 'development' | 'production' | 'test' | (string & {});
      TZ?: string;
      
      // Server-only environment variables (${nonPublicKeys.length} variables)
${nonPublicKeys.map((key) => `      ${key}: string;`).join("\n")}
      
      // Client-accessible environment variables (${
        publicKeys.length
      } variables)
${publicKeys.map((key) => `      ${key}: string;`).join("\n")}
      
    //   // Common web server variables
    //   PORT?: string;
    //   HOST?: string;
      
    //   // Database variables (common patterns)
    //   DATABASE_URL?: string;
    //   DB_HOST?: string;
    //   DB_PORT?: string;
    //   DB_USER?: string;
    //   DB_PASSWORD?: string;
    //   DB_NAME?: string;
      
    //   // API keys (common patterns)
    //   API_KEY?: string;
    //   API_SECRET?: string;
    //   API_URL?: string;
      
    //   // Authentication (common patterns)
    //   JWT_SECRET?: string;
    //   SESSION_SECRET?: string;
      
    //   // External services
    //   REDIS_URL?: string;
    //   AWS_ACCESS_KEY_ID?: string;
    //   AWS_SECRET_ACCESS_KEY?: string;
      
    //   // Monitoring
    //   SENTRY_DSN?: string;
    //   LOG_LEVEL?: string;
    }
  }
}

// Ensure this is treated as a module
export {};
`;

  try {
    // Create directory if it doesn't exist
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    // Read existing file to compare
    let existingContent = "";
    try {
      existingContent = fs.readFileSync(outputPath, "utf8");
    } catch {
      // File doesn't exist, that's fine
    }

    // Only write if content changed
    if (existingContent !== declarationContent) {
      fs.writeFileSync(outputPath, declarationContent, "utf8");
      console.log(`✨ Generated TypeScript declarations: ${outputPath}`);
      console.log(`   Detected ${keysArray.length} environment variables`);

      const declarationFile = path.basename(outputPath);
      updateFiles(declarationFile);
    }
  } catch (error) {
    console.warn(`⚠️  Could not generate TypeScript declarations:`, error);
  }
}
