import fs from "fs";
import path from "path";
import type { LoadOptions } from "../types.js";

/**
 * Generate a centralized `env.ts` file with all loaded environment variables.
 * Respects user-defined files.
 * @param keys Set of environment variable names to export
 */
export function generateEnvFileImpl(
  keys: Set<string>,
  generateEnvFile: LoadOptions["generateEnvFile"]
) {
  const isClient = isClientFramework();

  if (!generateEnvFile || keys.size === 0) return;

  if (isClient) {
    console.log("⚠️ Skipping env.ts generation: client framework detected.");
    return;
  }

  const cwd = process.cwd();

  const outputPath =
    typeof generateEnvFile === "string"
      ? generateEnvFile
      : path.resolve(cwd, "env.ts");

  // Determine target directory: src/lib if src exists, else lib
  const srcDir = path.join(cwd, "src");
  let targetDir: string;

  if (typeof generateEnvFile === "string") {
    targetDir = path.dirname(generateEnvFile);
  } else {
    if (fs.existsSync(srcDir)) {
      targetDir = path.join(srcDir, "lib");
    } else {
      targetDir = path.join(cwd, "lib");
    }
  }

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const filePath = path.join(targetDir, path.basename(outputPath));

  // Sort keys alphabetically for readability
  const keysArray = ["NODE_ENV", ...Array.from(keys).sort()];

  const exportBlock = `export const {
${keysArray.map((key) => `  ${key},`).join("\n")}
} = process.env;`;

  const fileContent = `// Auto-generated by @explita/env-loader
// Do not edit manually
import "@explita/env-loader/auto";

${exportBlock}
`;

  let existingContent = "";
  try {
    existingContent = fs.readFileSync(filePath, "utf8");
  } catch {
    // file doesn't exist yet
  }

  // Respect user-defined files
  if (
    existingContent &&
    !existingContent.includes("Auto-generated by @explita/env-loader")
  ) {
    console.log(
      `⚠️ ${filePath} exists and appears to be user-defined. Skipping update.`
    );
    return;
  }

  // Only write/update if our content changed or file is empty
  if (existingContent !== fileContent) {
    fs.writeFileSync(filePath, fileContent, "utf8");
    console.log(`✨ Generated env.ts: ${filePath}`);
    console.log(`   Exported ${keysArray.length} environment variables`);
  }
}

function isClientFramework() {
  const files = [
    "next-env.d.ts",
    "next.config.ts",
    "next.config.js",
    "next.config.mjs",
    "vite.config.ts",
    "vite.config.js",
    "vite.config.mjs",
  ];
  return files.some((f) => fs.existsSync(path.join(process.cwd(), f)));
}
